version: '3.8'

services:
  postgres-exporter-eptdb:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-eptdb
    environment:
      DATA_SOURCE_NAME: postgresql://user:pass@ip:port/db?sslmode=require
    ports:
      - "9187:9187"
   
    restart: always

  postgres-exporter-dwh:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-dwh
    environment:
      DATA_SOURCE_NAME: postgresql://user:pass@ip:port/db?sslmode=require
    ports:
      - "9188:9187"
  
    restart: always

  postgres-exporter-dev:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-dev
    environment:
      DATA_SOURCE_NAME: postgresql://user:pass@ip:port/db?sslmode=require
    ports:
      - "9189:9187"
   
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/dwh-prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: always

  

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  
    restart: always


volumes:
  prometheus-data:
  grafana-data: