global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgres-exporter-eptdb"
    static_configs:
      - targets: ["postgres-exporter-eptdb:9187"]
  - job_name: "postgres-exporter-dwh"
    static_configs:
      - targets: ["postgres-exporter-dwh:9187"]
  - job_name: "postgres-exporter-dev"
    static_configs:
      - targets: ["postgres-exporter-dev:9187"]
